# Generated by Django 3.2.23 on 2023-12-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productvariant_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
