# Generated by Django 3.2.23 on 2024-01-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, choices=[('Regular (Classic)', 'Regular (Classic)'), ('Slim', 'Slim'), ('Loose', 'Loose'), ('Athletic', 'Athletic'), ('Relaxed', 'Relaxed'), ('Skinny', 'Skinny')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
