# Generated by Django 3.2.23 on 2024-01-04 14:05

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240104_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
