# Generated by Django 3.2.23 on 2024-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
